/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.demo.sample_open_api.interfaces.rest;

import com.example.demo.sample_open_api.interfaces.rest.dto.CreateEntityRequestDto;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-09-15T08:31:22.943460600-03:00[America/Buenos_Aires]")
@Validated
@Api(value = "Default", description = "the Default API", tags={ "Default" })
public interface DefaultApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /entity : Create entity
     *
     * @param createEntityRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "Create entity", nickname = "entityPost", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK") })
    @PostMapping(
        value = "/entity",
        consumes = "application/json"
    )
    default ResponseEntity<Void> entityPost(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) CreateEntityRequestDto createEntityRequestDto) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
